name: home_bank
description: "A home banking client application for my children."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
repository: https://github.com/Vodichian/home_bank

version: 1.31.1+0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.0
  image_picker: ^1.1.2
  mobile_scanner: ^7.0.1
  permission_handler: ^12.0.1
  file_picker: ^10.3.2
  cupertino_icons: ^1.0.6
  go_router: ^16.0.0
  provider: ^6.1.2
  logger: ^2.3.0
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  bank_server:
    path: ../bank_server
  uuid: ^4.5.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^3.16.10
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/executables/bank_card_generator/
    - assets/executables/bank_card_generator/data/
    - assets/executables/bank_card_generator/data/flutter_assets/
    - assets/executables/bank_card_generator/data/flutter_assets/shaders/
    - assets/executables/bank_card_generator/data/flutter_assets/packages/cupertino_icons/assets/
    - assets/executables/bank_card_generator/data/flutter_assets/fonts/
    - assets/logo.png

msix_config:
  display_name: Home Bank
  publisher_display_name: Vodichian
  identity_name: com.vodichian.homebank
  msix_version: 1.31.1.0
  logo_path: assets\logo.png
  capabilities: "internetClient"
  certificate_path: C:\Users\ricks\Development\certificate\HomeBank.pfx
